"""add gpx_data table

Revision ID: 1d01ff305bcf
Revises: 0e34b3c53fa4
Create Date: 2021-11-17 09:20:03.560429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d01ff305bcf"
down_revision = "0e34b3c53fa4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpx_data",
        sa.Column("point_uuid", sa.String(), nullable=False),
        sa.Column("ride_uuid", sa.String(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=False),
        sa.Column("step_distance", sa.Float(), nullable=True),
        sa.Column("cum_distance", sa.Float(), nullable=True),
        sa.Column("mark", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ride_uuid"],
            ["ride.ride_uuid"],
        ),
        sa.PrimaryKeyConstraint("point_uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gpx_data")
    # ### end Alembic commands ###
