"""add cum_distance

Revision ID: a4403b8279da
Revises: df8834f0ea5f
Create Date: 2021-11-18 23:41:05.388559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4403b8279da"
down_revision = "df8834f0ea5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ride", sa.Column("cum_distance", sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ride") as batch_op:
        batch_op.drop_column("cum_distance")
    # ### end Alembic commands ###
