"""add last segment

Revision ID: b6ff6a01eca6
Revises: 4a1ce83f57dd
Create Date: 2021-04-25 14:20:26.599086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6ff6a01eca6"
down_revision = "4a1ce83f57dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ride", sa.Column("last_segment", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ride", "last_segment")
    # ### end Alembic commands ###
