"""drop gpx_data column

Revision ID: df8834f0ea5f
Revises: 1d01ff305bcf
Create Date: 2021-11-17 09:21:49.041454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "df8834f0ea5f"
down_revision = "1d01ff305bcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column("ride", "gpx")
    with op.batch_alter_table("ride") as batch_op:
        batch_op.drop_column("gpx")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ride", sa.Column("gpx", sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
